name: Android CI

on:
  push:
    branches: [ "kbzpay" ]
  pull_request:
    branches: [ "kbzpay" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Mg Aung Myat Oi
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for kbzpay
      run: chmod +x kbzpay
    - name: Build with KbzPay
      run: ./kbzpay build
